### ISSUE TITLE
Iskalnik

### ISSUE THREAD

**Issue by JernejcicZan** [JernejcicZan/OPB-Spletna-trgovina#1]
Pozdravljeni 
V datoteki artikli.html bi imel rad iskalnik po artiklih. Ko bi nekaj napisal vanj, bi prikazalo le vrstice s vpisanim nizom.
Poskusil sem nekaj podobnega kot na predavanjih pa mi ne deluje.
Sicer sem z ostalim skoraj zaključil. Bi bilo še kaj za popraviti?

**Comment by jaanos** [comment]
Da bo iskalnik deloval, bo potrebno znački `table` s tabelo dodati še atribut `id="izpis"`.

Glede na to, da se ti najbrž mudi, se lahko z @alenFMF domeniš za termin dogovora. Ko boš imel pripravljeno končno različico, mi javi, da dodam povezavo na repozitorij predmeta.

Imam še naslednje pripombe:

* V tabeli `narocila` manjka glavni ključ. Verjetno bo najbolje, da dodaš stolpec za ID tipa `SERIAL`.

* Tudi pri ostalih tabelah naj bo `id` tipa `SERIAL`, da ne bo potrebno pri dodajanju izdelkov in uporabnikov ročno izbirati ID-jev.

* Pri poljih, ki ustrezajo stolpcem tipa `boolean`, namesto vnosnega polja uporabi možnost obkljukanja (*checkbox*) - tako bo tudi bolj jasno, kaj je sploh mišljeno pri takem polju. Razmisli tudi o drugih možnih tipih vnosov (npr. izbirna polja z vnaprej določenimi možnostmi).

* Namesto obrazca za naročila, kjer je potrebno vnesti ID izdelka, bi bilo bolje imeti stran za vsak izdelek posebej, kjer se ta obraze pojavi.

* Premisli še, če lahko narediš prijavo uporabnika - potem pri naročanju tudi ne bo potrebno vpisovati ID-ja uporabnika, pač pa se uporabi ID prijavljenega uporabnika.

* V primeru, da pride do napake pri poizvedbah, aplikacija neha delovati. Da se temu izogneš, bo najbolje, da vsaj pri poizvedbah, ki spreminjajo bazo, poskrbiš za `rollback` v primeru napake, npr.:
```python
try:
    cur.execute(...)
    conn.commit() # poizvedba je šla skozi, shranimo in preusmerimo
except: # prišlo je do napake, prekličemo poizvedbo in prikažemo stran z napako
    conn.rollback()
    return rtemplate(..., napaka='...')
redirect(...)
```

* Svetujem, da poskrbiš, da bo aplikacija delovala na Binderju. Kolikor vidim, že uporabljaš `rtemplate` in povezave v predlogah začenjaš s spremenljivko `ROOT`, bo pa treba slednje storiti tudi pri `redirect`-ih in poskrbeti še za mapo `binder` (v `requirements.txt` bo potrebno dodati še `bottle`, če ga ne boš imel na samem repozitoriju). Za več podrobnosti glej jan248/Borza#1.

**Comment by JernejcicZan** [comment]
Sem naletel pri popravljanju na nekaj težav.

- Pri dodajanju novega uporabnika sem dodal možnost izbire Zaposlen Da/Ne. Ko dodam novega uporabnika se ta sicer doda v bazo a namesto da bi me redirectalo na uporabnike me spet na dodajanje novega uporabnika

- Pri artiklih sem dodal možnost naročitve takoj zraven. Ko naj bi se izdelek naročil pa mi javlja napako
  File "C:\Users\Uporabnik\Documents\žan\faks\3.letnik\OPB-Spletna-trgovina\views\oddaj_narocilo.html", line 13, in <module>
   <input name="id_izdelka" type="text" value="{{id_izdelka}}">
NameError: name 'id_izdelka' is not defined

- Če pogledam pogledam naročila na http://localhost:8080/narocila imam tam stolpec popust, ki sem ga izbrisal pa je še zmeraj tam in manjka stolpec stevilka_narocila tako da je vse zamaknjeno.
LP Žan

**Comment by jaanos** [comment]
Glede dodajanja uporabnika je problem, da `redirect` sproži izjemo, zato ga je potrebno izvesti izven `try` (sem popravil primer v zgornjem odgovoru). Še bolje bi sicer bilo pri `except` specificirati, za katere izjeme naj se zgodijo sledeče vrstice.

Mimogrede, tega ne počni:
https://github.com/JernejcicZan/OPB-Spletna-trgovina/blob/2f4ec2809ec3961c3986513bf3f31e406868d12a/trgovina.py#L60-L61
Vidim, da si zdaj naredil stolpce s tipom `SERIAL`, tako da lahko ustrezne stolpce pri dodajanju enostavno izpustiš. Glede na to, da si sicer ohranil obstoječe ID-je v tabelah, bo potrebno števcem (v phppgadmin-u jih najdeš pod *Sequences*) na roke nastaviti trenutno vrednost, da bo dodajanje potekalo, kot mora.

Pri naročanju, če natančneje pogledaš napako, se ta nanaša na to vrstico:
https://github.com/JernejcicZan/OPB-Spletna-trgovina/blob/2f4ec2809ec3961c3986513bf3f31e406868d12a/trgovina.py#L128
Tukaj vrednost `izdelek` dobiš iz polja `id_izdelka`, ki pa ni specificirano in je zato ta vrednost prazna (in pride do napake pri pretvorbi v število). Treba bo torej vključiti ID izdelka - lahko ga vključiš v sam URL (npr. `/oddaj_narocilo/<izdelek>`), ali pa v obrazec dodaš skrito polje, npr.
```html
<input name="id_izdelka" type="hidden" value="{{id_izdelka}}">
```

Pri naročilih bo pa potrebno enostavno v predlogi popraviti imena stolpcev in spremenljivk (ker izbiraš s `SELECT * ...`, je vrstni red podatkov tak kot v bazi).

**Comment by JernejcicZan** [comment]
Sem popravil večino. Pri števcih v phpPgadminu pa imam težave, recimo ko želim nastaviti (alter) za artikli_id_seq mi vrne napako 
ERROR. permission denied for relation artikli_id_seq
V binderju mi sicer odpre začetno stran ampak ne izgleda enako (poravnava, gumbi). Ko kliknem na Naroči pri artiklih pa javi napako.
LP Žan

**Comment by jaanos** [comment]
Vidim, da imaš tabele (in posledično tudi števce) sedaj narejene z uporabnikom `javnost` - ker nisi dal sebi ustreznih pravic, tudi ne moreš spreminjati števca.

Bolje bo, če tabele ustvariš s svojim uporabniškim imenom (z ustreznimi ukazi `ALTER TABLE` in `ALTER SEQUENCE` lahko tudi obstoječim tabelam in števcem spremeniš lastnika), pa potem uporabniku `javnost` daš zadostne pravice na tabelah in števcih, npr.
```sql
GRANT CONNECT ON DATABASE sem2020_zanj TO javnost;
GRANT SELECT, INSERT ON ALL TABLES IN SCHEMA public TO javnost;
GRANT UPDATE ON artikli TO javnost;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA public TO javnost;
```

**Comment by JernejcicZan** [comment]
Sem rešil težavo z id-ji. Tudi v Binderju mi vse deluje, le zanima me zakaj ni pravi stil (poravnava, gumbi).
Sicer če ni drugih pripomb pa bi zaključil in lahko dodate povezavo na repozitorij.

**Comment by jaanos** [comment]
Stili na Binderju ne delujejo, ker manjka `ROOT` pri uvozu CSS-ja (in Javascripta):
https://github.com/JernejcicZan/OPB-Spletna-trgovina/blob/3c5f78299f5498a47d6a2be028c79e9dd0676869/views/baza.html#L11-L12

Opažam še, da si sedaj na repozitorij objavil datoteko `auth.py` s svojim geslom za bazo, ki je tako za vekomaj objavljeno na internetu. Svetujem ti, da ga zamenjaš in vrneš datoteko `auth_public.py` s podatki za prijavo z uporabnikom `javnost`, ki mu seveda daj ustrezne pravice (glej prejšnji odgovor).

Bom dodal povezavo do projekta na repozitorij predmeta, tako da se lahko z @alenFMF domeniš za termin zagovora, če se še nisi. Če boš do takrat še kaj spreminjal, mi javi, da posodobim povezavo.

**Comment by JernejcicZan** [comment]
Sem popravil ampak ne vem zakaj mi Binder vrne 500 : Internal Server Error

**Comment by jaanos** [comment]
Zdaj ti manjka `auth_public.py`, ki jo seveda uvozi v `trgovina.py`.

**Comment by JernejcicZan** [comment]
Sem popravil in dela kot mora.

**Comment by jaanos** [comment]
V redu, sem posodobil povezavo.
